# Generated by Django 3.1.5 on 2021-01-10 15:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=-AOPAqxAFJk'),
        ),
    ]
